// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu-wfW8Hms2MZQGd9kz_h3DwVgzfioL8M',
    appId: '1:545971557249:web:e989dc25d7af325fdece80',
    messagingSenderId: '545971557249',
    projectId: 'split-smart-43ee5',
    authDomain: 'split-smart-43ee5.firebaseapp.com',
    storageBucket: 'split-smart-43ee5.firebasestorage.app',
    measurementId: 'G-PPVL7BGMCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8nWHX17-L9nbk1MiE3ki7n_HMz4PcVfs',
    appId: '1:545971557249:android:6cc7f4928f766ab1dece80',
    messagingSenderId: '545971557249',
    projectId: 'split-smart-43ee5',
    storageBucket: 'split-smart-43ee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1BQ-iGGj5xKKi6qupUQ7W0XREHBYQspc',
    appId: '1:545971557249:ios:b16639f26ab4a079dece80',
    messagingSenderId: '545971557249',
    projectId: 'split-smart-43ee5',
    storageBucket: 'split-smart-43ee5.firebasestorage.app',
    iosBundleId: 'com.example.splitSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1BQ-iGGj5xKKi6qupUQ7W0XREHBYQspc',
    appId: '1:545971557249:ios:b16639f26ab4a079dece80',
    messagingSenderId: '545971557249',
    projectId: 'split-smart-43ee5',
    storageBucket: 'split-smart-43ee5.firebasestorage.app',
    iosBundleId: 'com.example.splitSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu-wfW8Hms2MZQGd9kz_h3DwVgzfioL8M',
    appId: '1:545971557249:web:b2346342ff046a59dece80',
    messagingSenderId: '545971557249',
    projectId: 'split-smart-43ee5',
    authDomain: 'split-smart-43ee5.firebaseapp.com',
    storageBucket: 'split-smart-43ee5.firebasestorage.app',
    measurementId: 'G-WTPG26581F',
  );
}
